@startuml
skinparam backgroundcolor transparent
skinparam shadowing false

left to right direction

class Player {
    name
}

class Hand

class Game

class Deck

class Card

class CardType {
    color
    type
}

Player "1"<--"*" Hand
Player "*"--"*" Game
(Player, Game) .. Play


Game "1"<--"*" Hand
Game "1"--"1" Deck

Deck "1"<--"*" Card
Card "*"-->"1" CardType
Card "*"-->"1" Hand
@enduml