version: '3.1'

services:
  db:
    build: postgres-db
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
    ports:
      - 5432:5432
    volumes:
      - quiz-db-data:/var/lib/postgresql

volumes:
  quiz-db-data: